language: ruby
rvm:
  - 2.3.1
before_install: gem install bundler -v 1.11.2
sudo: required
addons:
  apt:
    packages:
      - libsdl2-dev
      - libsdl2-ttf-dev
      - libpango1.0-dev
      - libgl1-mesa-dev
      - libfreeimage-dev
      - libopenal-dev
      - libsndfile1-dev
